/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.potato;

public class Library {
    public static void main(String[] args) {
        System.out.println("hahahahahaha");
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
