/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    public void testNoErrorsFile() {
        String allData = App.readFiles("src/test/resources/noErrors.js");
        assertTrue(!allData.contains("Missing semicolon."));
    }

    @Test
    public void testEmptyFile() {
        String allData = App.readFiles("src/test/resources/empty.js");
        assertTrue(!allData.contains("Missing semicolon."));
    }

    @Test
    public void oneErrorTest() {
        String allData = App.readFiles("src/test/resources/oneError.js");
        assertTrue(allData.contains("Missing semicolon."));
    }

    @Test
    public void fewErrorsTest() {
        String allData = App.readFiles("src/test/resources/fewErrors.js");
        assertTrue(allData.contains("Missing semicolon."));
    }

    @Test
    public void manyErrorsTest() {
        String allData = App.readFiles("src/test/resources/manyErrors.js");
        assertTrue(allData.contains("Missing semicolon."));
    }


}
